// Generated by gencpp from file track8yolo/BoundingBox.msg
// DO NOT EDIT!


#ifndef TRACK8YOLO_MESSAGE_BOUNDINGBOX_H
#define TRACK8YOLO_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace track8yolo
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , label(0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , label(0)  {
  (void)_alloc;
    }



   typedef int64_t _xmin_type;
  _xmin_type xmin;

   typedef int64_t _ymin_type;
  _ymin_type ymin;

   typedef int64_t _xmax_type;
  _xmax_type xmax;

   typedef int64_t _ymax_type;
  _ymax_type ymax;

   typedef int64_t _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::track8yolo::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::track8yolo::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::track8yolo::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::track8yolo::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::track8yolo::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::track8yolo::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::track8yolo::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::track8yolo::BoundingBox_<ContainerAllocator1> & lhs, const ::track8yolo::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax &&
    lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::track8yolo::BoundingBox_<ContainerAllocator1> & lhs, const ::track8yolo::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace track8yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::track8yolo::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::track8yolo::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::track8yolo::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::track8yolo::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::track8yolo::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::track8yolo::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::track8yolo::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3356b77b350c7150522a34c60a8a840";
  }

  static const char* value(const ::track8yolo::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3356b77b350c715ULL;
  static const uint64_t static_value2 = 0x0522a34c60a8a840ULL;
};

template<class ContainerAllocator>
struct DataType< ::track8yolo::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "track8yolo/BoundingBox";
  }

  static const char* value(const ::track8yolo::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::track8yolo::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
"int64 label\n"
;
  }

  static const char* value(const ::track8yolo::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::track8yolo::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::track8yolo::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::track8yolo::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "xmin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymax);
    s << indent << "label: ";
    Printer<int64_t>::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACK8YOLO_MESSAGE_BOUNDINGBOX_H
