// Generated by gencpp from file ros_learn/add.msg
// DO NOT EDIT!


#ifndef ROS_LEARN_MESSAGE_ADD_H
#define ROS_LEARN_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <ros_learn/addRequest.h>
#include <ros_learn/addResponse.h>


namespace ros_learn
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace ros_learn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_learn::add > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_learn::add&) { return value(); }
};

template<>
struct DataType< ::ros_learn::add > {
  static const char* value()
  {
    return "ros_learn/add";
  }

  static const char* value(const ::ros_learn::add&) { return value(); }
};


// service_traits::MD5Sum< ::ros_learn::addRequest> should match
// service_traits::MD5Sum< ::ros_learn::add >
template<>
struct MD5Sum< ::ros_learn::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_learn::add >::value();
  }
  static const char* value(const ::ros_learn::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_learn::addRequest> should match
// service_traits::DataType< ::ros_learn::add >
template<>
struct DataType< ::ros_learn::addRequest>
{
  static const char* value()
  {
    return DataType< ::ros_learn::add >::value();
  }
  static const char* value(const ::ros_learn::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_learn::addResponse> should match
// service_traits::MD5Sum< ::ros_learn::add >
template<>
struct MD5Sum< ::ros_learn::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_learn::add >::value();
  }
  static const char* value(const ::ros_learn::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_learn::addResponse> should match
// service_traits::DataType< ::ros_learn::add >
template<>
struct DataType< ::ros_learn::addResponse>
{
  static const char* value()
  {
    return DataType< ::ros_learn::add >::value();
  }
  static const char* value(const ::ros_learn::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_LEARN_MESSAGE_ADD_H
